### ISSUE TITLE
Consider use of database enumerations

### ISSUE THREAD

**Issue by dr-rodriguez** [kelle/SIMPLE#27]
Enumerations are a way of enforcing that only certain values get into the database. Attempting to add one that isn't listed would give an error. Here are two that we could consider:
```
class Regime(enum.Enum):
    """Enumeration for spectral type regime"""
    optical = 'optical'
    infrared = 'infrared'
    ultraviolet = 'ultraviolet'
    radio = 'radio'

class Gravity(enum.Enum):
    """Enumeration for gravity"""
    a = 'alpha'
    b = 'beta'
    g = 'gamma'
    bg = 'beta/gamma'
    unknown = 'unknown'
```
We would have to test this functionality with Astrodbkit2 before we commit to it.

**Comment by Will-Cooper** [comment]
Recommend close @dr-rodriguez
