### ISSUE TITLE
Simple as a package

### ISSUE THREAD

**Issue by Will-Cooper** [kelle/SIMPLE#31]
Current <i>environment.yml</i> is the required dependencies/ conda environment for astrodbkit2, not simple. Do we want to add simple as a requirement to that environment or are we expecting people to operate in the cloned simple directory; i.e. in the same location as simple/schema.py and simple.db?

**Comment by kelle** [comment]
Astrodbkit2 is meant to work with lots of databases, not just SIMPLE. So Astrodbkit2 is a dependency of SIMPLE, but not the other way around.

Also, SIMPLE is at it's most fundamental, a collection of text (.json) files, not python code, so it's not quite right to "package" it. However, we might want to consider offering a binary version of the database as an easy to use, one click download thing which one could open with SQLite Browser, for example.
