### ISSUE TITLE
Duplicate WISE photometry

### ISSUE THREAD

**Issue by Will-Cooper** [kelle/SIMPLE#64]
At current I find 676 objects in ```SIMPLE.db```. Of these, 341 have photometry; of those I find 8 have duplicate WISE photometry for W1-W3:
```bash
2MASSI J0953212-101420
TWA 28
2MASS J00274197+0503417
2MASS J12451416-4429077
2MASS J07290002-3954043
TWA 26
2MASS J00470038+6803543
2MASS J21140802-2251358
```
The values are _slightly_ different, I think from the different surveys: Cutr12 & Cutr13.
What do we want to do in these cases?

**Comment by dr-rodriguez** [comment]
I'll have to double check, but if they have different references then by definition they aren't duplicates. This is to account for the fact that multiple studies can observe the same target with the same filter. The uniqueness of a row is the combination of source, band, and reference.

**Comment by Will-Cooper** [comment]
Sounds like this is a non-issue
