### ISSUE TITLE
add epoch and equinox to sources table

### ISSUE THREAD

**Issue by kelle** [kelle/SIMPLE#73]
Per #72 : In order to be able to astropy.coordinates to predict coordinates of objects at any date, we need epoch and equinox of the coordinate in the sources table.

**Comment by dr-rodriguez** [comment]
We probably want to store equinox as a string (eg, J2000), but for epoch, do we want to store it as floats (2015.0), strings ('2015-01-01'), or `datetime.Date`(or `DateTime`) objects? 
Strings are probably easiest, but Date might allow for more powerful searches- if that were a use case.
For proper motion calculations, this would have to be converted to `astropy.time.Time` objects regardless.
