### ISSUE TITLE
Design data integrity tests

### ISSUE THREAD

**Issue by kelle** [kelle/SIMPLE#9]
We want to have some automated tests which confirm the contents of the database are what we expect. E.g, 
 - there should be # of spectra referenced to Cruz 2018.
 - there should be # of sources referenced to Gagne 2010.
 - ...

I think these tests should be added as we ingest data. Please put more ideas for data integrity tests in this issue.

**Comment by kelle** [comment]
@dr-rodriguez enforced some tests while putting together #13 . David, could you list them here? And I will try to code them up.

**Comment by dr-rodriguez** [comment]
The boiler plate code in #16 provides the tests I carried out, though I relied on the database enforcement of primary/foreign keys for a lot of it.
In short: I verified publication and source name uniqueness, reference links, and not-null coordinates. 

Let me know if you want me to provide more detail in terms of how to use the Astrodbkit2 API to perform these checks.

**Comment by kelle** [comment]
Many of these were implemented in #35 and #36. @dr-rodriguez , think this issue can be closed?

**Comment by dr-rodriguez** [comment]
Sure, let's close for now and we can have more specific tests/issues as we move forward with this.
